image: python:3.8

stages:
  - test

test:
  stage: test
  script:
    - pip install poetry
    - poetry install -v
    - poetry run tox
    - poetry run coverage run -m pytest
    - poetry run coverage report
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  tags:
    - docker
